apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api-feed
  labels:
    app: backend-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-api-feed
  template:
    metadata:
      labels:
        app: backend-api-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: benjosiah/udagram-api-feed
        ports:
        - containerPort: 80