apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: benjosiah/udagram-api-user:v1
        envFrom:
          - secretRef:
              name: env-secret
          - secretRef:
              name: aws-secret
          - configMapRef:
              name: config-map
        resources:
          requests:
            memory: "1000Mi"
            cpu: "100m"
          limits:
            memory: "2000Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080