apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: benjosiah/udagram-api-user:v1
        resources:
          requests:
            memory: "30000Mi"
          limits:
            memory: "40000Mi"
        ports:
        - containerPort: 80