apiVersion: v1
kind: Service
metadata:
  name: backend-feed
  labels:
    run: backend-feed
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    run: backend-feed