apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api-user
  labels:
    app: backend-api-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-api-user
  template:
    metadata:
      labels:
        app: backend-api-user
    spec:
      containers:
      - name: udagram-api-user
        image: benjosiah/udagram-api-user
        ports:
        - containerPort: 80